import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { HiHome } from "react-icons/hi2";
import { TbAlertTriangle, TbShieldCheck, TbFlame, TbCopy, TbArrowRight, TbCheck, TbRefresh, TbDownload } from "react-icons/tb";
import { motion, AnimatePresence } from "framer-motion";

const API_BASE = "https://abhedya-production.up.railway.app" || "http://localhost:8000"

const ISSUE_TYPES = [
  "Online Banking Fraud",
  "UPI / Payment Scam",
  "OTP / SIM Swap Fraud",
  "Phishing / Fake Website",
  "Investment / Trading Scam",
  "Social Media Hacking",
  "Ransomware / Malware",
  "Sextortion / Blackmail",
  "Job / Part-time Scam",
  "Other Cybercrime",
]

const SEVERITY_CONFIG = {
  high:   { color: "text-red-400",    bg: "bg-red-500/10 border-red-500/30",       glow: "shadow-[0_0_28px_rgba(239,68,68,0.12)]",  label: "HIGH RISK",   icon: TbFlame        },
  medium: { color: "text-yellow-400", bg: "bg-yellow-500/10 border-yellow-500/30", glow: "shadow-[0_0_28px_rgba(234,179,8,0.12)]",  label: "MEDIUM RISK", icon: TbAlertTriangle },
  low:    { color: "text-green-400",  bg: "bg-green-500/10 border-green-500/30",   glow: "shadow-[0_0_28px_rgba(34,197,94,0.12)]",  label: "LOW RISK",    icon: TbShieldCheck   },
}

const pageVariants = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0, transition: { duration: 0.45, ease: [0.16, 1, 0.3, 1] } },
  exit:    { opacity: 0, y: -16, transition: { duration: 0.25, ease: [0.4, 0, 1, 1] } },
}

const staggerContainer = {
  animate: { transition: { staggerChildren: 0.07, delayChildren: 0.05 } }
}

const staggerItem = {
  initial: { opacity: 0, y: 12 },
  animate: { opacity: 1, y: 0, transition: { duration: 0.35, ease: [0.16, 1, 0.3, 1] } },
}

const fieldClass = "w-full bg-zinc-900 border border-zinc-700 text-zinc-100 text-sm rounded-xl px-4 py-3 focus:outline-none focus:border-zinc-500 transition-all placeholder:text-zinc-600"

function FirstAid() {
  const [step, setStep]         = useState("form")
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState("")
  const [report, setReport]     = useState(null)
  const [copied, setCopied]     = useState(false)
  const [pdfLoading, setPdfLoading] = useState(false)

  const [form, setForm] = useState({
    issue_type:   "",
    description:  "",
    victim_name:  "",
    victim_phone: "",
    victim_city:  "",
    amount_lost:  "",
  })

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
    setError("")
  }

  const handleSubmit = async () => {
    if (!form.issue_type || !form.description.trim()) {
      setError("Please select an issue type and describe what happened.")
      return
    }
    if (form.description.trim().length < 30) {
      setError("Please describe the incident in at least 30 characters.")
      return
    }
    setLoading(true); setError("")
    try {
      const res = await fetch(`${API_BASE}/report/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          issue_type:  form.issue_type,
          description: form.description,
          victim_details: {
            name:        form.victim_name  || "Not provided",
            phone:       form.victim_phone || "Not provided",
            city:        form.victim_city  || "Not provided",
            amount_lost: form.amount_lost  || "Not provided",
          },
        }),
      })
      if (!res.ok) throw new Error("Server error. Please try again.")
      const data = await res.json()
      setReport(data)
      setStep("report")
    } catch (err) {
      setError(err.message || "Something went wrong. Please try again.")
    } finally {
      setLoading(false)
    }
  }

  const reportText = () => {
    if (!report) return ""
    return `
CYBERCRIME INCIDENT REPORT
==========================
Title: ${report.title}
Severity: ${report.severity?.toUpperCase()}
Incident Type: ${report.incident_type}

SUMMARY
-------
${report.summary}

TIMELINE
--------
${report.timeline?.map((t, i) => `${i + 1}. ${t}`).join('\n')}

TECHNICAL DETAILS
-----------------
${report.technical_details}

IMPACT
------
${report.impact}

RECOMMENDATIONS
---------------
${report.recommendations?.map((r, i) => `${i + 1}. ${r}`).join('\n')}

LEGAL REFERENCES
----------------
${report.legal_refs?.join(', ')}

Generated by Abhedya — cybercrime.gov.in | Helpline: 1930
    `.trim()
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadPDF = async () => {
    if (!report) return
    setPdfLoading(true)
    try {
      if (!window.jspdf) {
        await new Promise((resolve, reject) => {
          const script = document.createElement('script')
          script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
          script.onload = resolve
          script.onerror = reject
          document.head.appendChild(script)
        })
      }

      const { jsPDF } = window.jspdf
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })

      // Sanitize: fix special chars jsPDF can't render cleanly
      const clean = (str) => (str || '')
        .replace(/[\u2018\u2019]/g, "'")
        .replace(/[\u201C\u201D]/g, '"')
        .replace(/\u20B9/g, 'Rs.')
        .replace(/\u2013|\u2014/g, '-')
        .replace(/[^\x00-\x7F]/g, '')

      const pageW  = doc.internal.pageSize.getWidth()
      const pageH  = doc.internal.pageSize.getHeight()
      const margin = 18
      const cW     = pageW - margin * 2
      let y        = margin

      const sevRGB = report.severity === 'high'
        ? [220, 38, 38]
        : report.severity === 'medium'
        ? [202, 138, 4]
        : [22, 163, 74]

      // ── HEADER BAR ──────────────────────────────────────────────
      doc.setFillColor(12, 12, 12)
      doc.rect(0, 0, pageW, 22, 'F')

      // "Abhed" white + "ya" red — exact app logo style
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(15)
      doc.setTextColor(255, 255, 255)
      doc.text('Abhed', margin, 14.5)
      const abhedW = doc.getTextWidth('Abhed')
      doc.setTextColor(220, 38, 38)
      doc.text('ya', margin + abhedW, 14.5)

      // Tagline right side
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7.5)
      doc.setTextColor(160, 160, 160)
      doc.text('cybercrime.gov.in  |  Helpline: 1930', pageW - margin, 14.5, { align: 'right' })

      // Severity-colored accent line under header
      doc.setFillColor(...sevRGB)
      doc.rect(0, 22, pageW, 1.2, 'F')

      y = 32

      // ── REPORT TITLE ────────────────────────────────────────────
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(17)
      doc.setTextColor(20, 20, 20)
      doc.text('CYBERCRIME INCIDENT REPORT', margin, y)
      y += 8

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      doc.setTextColor(50, 50, 50)
      const titleLines = doc.splitTextToSize(clean(report.title), cW)
      titleLines.forEach(l => { doc.text(l, margin, y); y += 6 })
      y += 3

      // ── SEVERITY CHIP + TYPE ─────────────────────────────────────
      doc.setFillColor(...sevRGB)
      doc.roundedRect(margin, y, 36, 7.5, 1.8, 1.8, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7.5)
      doc.setTextColor(255, 255, 255)
      doc.text(`${(report.severity || 'medium').toUpperCase()} RISK`, margin + 18, y + 5, { align: 'center' })

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9.5)
      doc.setTextColor(70, 70, 70)
      doc.text(`Type: ${clean(report.incident_type)}`, margin + 42, y + 5)
      y += 14

      // ── DIVIDER ──────────────────────────────────────────────────
      doc.setDrawColor(210, 210, 210)
      doc.setLineWidth(0.25)
      doc.line(margin, y, pageW - margin, y)
      y += 9

      // ── PAGE-BREAK HELPER ────────────────────────────────────────
      const checkBreak = (need = 18) => {
        if (y + need > pageH - margin) {
          doc.addPage()
          y = margin
          // Mini header on continuation pages
          doc.setFillColor(12, 12, 12)
          doc.rect(0, 0, pageW, 14, 'F')
          doc.setFillColor(...sevRGB)
          doc.rect(0, 14, pageW, 0.8, 'F')
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(9)
          doc.setTextColor(255, 255, 255)
          doc.text('Abhed', margin, 9.5)
          const aw = doc.getTextWidth('Abhed')
          doc.setTextColor(220, 38, 38)
          doc.text('ya', margin + aw, 9.5)
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(7)
          doc.setTextColor(150, 150, 150)
          doc.text('Incident Report (cont.)', pageW - margin, 9.5, { align: 'right' })
          y = 22
        }
      }

      // ── SECTION LABEL ────────────────────────────────────────────
      const sectionLabel = (label) => {
        checkBreak(16)
        doc.setFillColor(240, 240, 240)
        doc.roundedRect(margin, y, cW, 6.5, 1, 1, 'F')
        // Left accent bar in severity color
        doc.setFillColor(...sevRGB)
        doc.roundedRect(margin, y, 2.5, 6.5, 0.5, 0.5, 'F')
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(7.5)
        doc.setTextColor(40, 40, 40)
        doc.text(label.toUpperCase(), margin + 6, y + 4.5)
        y += 10
      }

      // ── PARAGRAPH ────────────────────────────────────────────────
      const addPara = (text) => {
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9.5)
        doc.setTextColor(55, 55, 55)
        const lines = doc.splitTextToSize(clean(text), cW)
        lines.forEach(l => { checkBreak(6); doc.text(l, margin, y); y += 5.5 })
        y += 5
      }

      // ── NUMBERED LIST ────────────────────────────────────────────
      const addNumberedList = (items) => {
        items.forEach((item, i) => {
          checkBreak(8)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(9)
          doc.setTextColor(...sevRGB)
          doc.text(String(i + 1).padStart(2, '0'), margin, y)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(55, 55, 55)
          const lines = doc.splitTextToSize(clean(item), cW - 9)
          lines.forEach((l, li) => {
            checkBreak(6)
            doc.text(l, margin + 9, y)
            if (li < lines.length - 1) y += 5.5
          })
          y += 6.5
        })
        y += 3
      }

      // ── CHECK LIST ───────────────────────────────────────────────
      const addCheckList = (items) => {
        items.forEach((item) => {
          checkBreak(8)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(9)
          doc.setTextColor(22, 163, 74)
          doc.text('+', margin, y)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(55, 55, 55)
          const lines = doc.splitTextToSize(clean(item), cW - 7)
          lines.forEach((l, li) => {
            checkBreak(6)
            doc.text(l, margin + 6, y)
            if (li < lines.length - 1) y += 5.5
          })
          y += 6.5
        })
        y += 3
      }

      // ── RENDER SECTIONS ──────────────────────────────────────────
      if (report.summary) {
        sectionLabel('Summary')
        addPara(report.summary)
      }

      if (report.timeline?.length) {
        sectionLabel('Timeline')
        addNumberedList(report.timeline)
      }

      if (report.technical_details) {
        sectionLabel('Technical Analysis')
        addPara(report.technical_details)
      }

      if (report.impact) {
        sectionLabel('Impact Assessment')
        addPara(report.impact)
      }

      if (report.recommendations?.length) {
        sectionLabel('What To Do Now')
        addCheckList(report.recommendations)
      }

      if (report.legal_refs?.length) {
        sectionLabel('Applicable Law')
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        doc.setTextColor(55, 55, 55)
        const refsLines = doc.splitTextToSize(clean(report.legal_refs.join('  |  ')), cW)
        refsLines.forEach(l => { checkBreak(6); doc.text(l, margin, y); y += 5.5 })
        y += 4
      }

      // ── FOOTER ───────────────────────────────────────────────────
      checkBreak(14)
      doc.setDrawColor(210, 210, 210)
      doc.setLineWidth(0.25)
      doc.line(margin, y, pageW - margin, y)
      y += 5.5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7.5)
      doc.setTextColor(140, 140, 140)
      const dateStr = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
      doc.text(`Generated by Abhedya on ${dateStr} IST`, margin, y)
      doc.text('cybercrime.gov.in  |  1930', pageW - margin, y, { align: 'right' })

      const filename = `Abhedya_${(report.incident_type || 'Report').replace(/\s+/g, '_')}_${Date.now()}.pdf`
      doc.save(filename)
    } catch (e) {
      console.error('PDF error:', e)
    } finally {
      setPdfLoading(false)
    }
  }

  const sev     = report ? (SEVERITY_CONFIG[report.severity] || SEVERITY_CONFIG.medium) : null
  const SevIcon = sev?.icon

  return (
    <div className="relative w-full min-h-screen bg-black text-zinc-200 overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-br from-black via-red-400 to-black opacity-80" />
      <div className="absolute inset-0 bg-black/70" />

      {/* Navbar */}
      <nav className="relative z-20 flex items-center justify-between px-6 sm:px-10 md:px-16 pt-6">
        <h1 className="font-poppins text-2xl text-zinc-50">
          Abhed<span className="text-red-500">ya</span>
        </h1>
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 font-sans text-sm text-white px-3 py-1.5 rounded-full border border-zinc-700 hover:border-red-500 hover:text-red-500 transition-colors duration-200 whitespace-nowrap"
        >
          <HiHome size={16} />
          <span>BACK TO HOME</span>
        </Link>
      </nav>

      <div className="relative z-10 w-full max-w-2xl mx-auto px-6 sm:px-10 md:px-0 py-10">

        {/* Header */}
        <motion.div
          className="mb-8 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        >
          <div className="inline-flex items-center gap-2 mb-3">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
            <span className="text-xs font-sans tracking-widest text-red-400 uppercase">Cyber First Aid</span>
          </div>
          <AnimatePresence mode="wait">
            <motion.h2
              key={step}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
              className="text-3xl sm:text-4xl font-semibold text-zinc-50 leading-tight tracking-tight"
            >
              {step === "form" ? "Report an Incident" : "Your Incident Report"}
            </motion.h2>
          </AnimatePresence>
          <p className="mt-2 text-sm text-zinc-500">
            {step === "form"
              ? "Fill in the details. We'll generate a report you can use to file a complaint."
              : "Share this report with cybercrime.gov.in or your nearest police station."}
          </p>
        </motion.div>

        <AnimatePresence mode="wait">

          {/* ── FORM STEP ── */}
          {step === "form" && (
            <motion.div key="form" variants={pageVariants} initial="initial" animate="animate" exit="exit">
              <motion.div className="space-y-4" variants={staggerContainer} initial="initial" animate="animate">

                {/* Issue Type */}
                <motion.div variants={staggerItem}>
                  <label className="block text-[10px] font-sans tracking-widest text-zinc-500 mb-2 uppercase">
                    Type of Incident <span className="text-red-500">*</span>
                  </label>
                  <select
                    name="issue_type"
                    value={form.issue_type}
                    onChange={handleChange}
                    className={fieldClass + " cursor-pointer"}
                    style={{ colorScheme: 'dark' }}
                  >
                    <option value="">Select incident type...</option>
                    {ISSUE_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </motion.div>

                {/* Description */}
                <motion.div variants={staggerItem}>
                  <label className="block text-[10px] font-sans tracking-widest text-zinc-500 mb-2 uppercase">
                    What happened? <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    name="description"
                    value={form.description}
                    onChange={handleChange}
                    rows={5}
                    placeholder="Describe the incident in detail — when it happened, how you were contacted, what was asked of you, what you lost..."
                    className={fieldClass + " resize-none"}
                  />
                  <p className="mt-1 text-[10px] font-sans text-zinc-700 text-right">{form.description.length} chars</p>
                </motion.div>

                {/* Optional fields */}
                <motion.div variants={staggerItem} className="bg-zinc-900/60 border border-zinc-800 rounded-2xl p-5 space-y-4">
                  <div className="flex items-center gap-2">
                    <span className="w-0.5 h-3.5 rounded-full bg-zinc-600" />
                    <p className="text-[10px] font-sans tracking-widest text-zinc-500 uppercase">Optional — helps generate a stronger report</p>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {[
                      { name: "victim_name",  label: "Your Name",       placeholder: "e.g. Rahul Sharma" },
                      { name: "victim_phone", label: "Phone Number",    placeholder: "e.g. 98XXXXXXXX"   },
                      { name: "victim_city",  label: "City",            placeholder: "e.g. Siliguri"     },
                      { name: "amount_lost",  label: "Amount Lost (Rs.)", placeholder: "e.g. 15000"      },
                    ].map(f => (
                      <div key={f.name}>
                        <label className="block text-[10px] font-sans text-zinc-600 mb-1.5 uppercase tracking-wider">{f.label}</label>
                        <input
                          name={f.name}
                          value={form[f.name]}
                          onChange={handleChange}
                          placeholder={f.placeholder}
                          className={fieldClass + " py-2.5"}
                        />
                      </div>
                    ))}
                  </div>
                </motion.div>

                {/* Error */}
                <AnimatePresence>
                  {error && (
                    <motion.div
                      initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                      className="flex items-start gap-2 text-sm text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-3"
                    >
                      <span className="shrink-0 mt-0.5">⚠</span><span>{error}</span>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Submit */}
                <motion.button
                  variants={staggerItem}
                  onClick={handleSubmit}
                  disabled={loading}
                  whileHover={{ scale: 1.01 }}
                  whileTap={{ scale: 0.98 }}
                  className="w-full flex items-center justify-center gap-2 py-3.5 rounded-xl bg-red-600 hover:bg-red-500 disabled:opacity-40 disabled:cursor-not-allowed text-white text-sm font-semibold tracking-wide transition-colors duration-200"
                >
                  {loading ? (
                    <>
                      <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                      </svg>
                      Generating Report...
                    </>
                  ) : (
                    <>Generate Report <TbArrowRight size={15} /></>
                  )}
                </motion.button>

                {/* Emergency strip */}
                <motion.div variants={staggerItem} className="flex items-center justify-between text-xs text-zinc-600 bg-zinc-900/40 border border-zinc-800/50 rounded-xl px-4 py-3">
                  <span>Cybercrime Helpline</span>
                  <a href="tel:1930" className="text-red-500/70 font-sans font-semibold hover:text-red-400 transition-colors tracking-widest">1930</a>
                </motion.div>

              </motion.div>
            </motion.div>
          )}

          {/* ── REPORT STEP ── */}
          {step === "report" && report && (
            <motion.div key="report" variants={pageVariants} initial="initial" animate="animate" exit="exit">
              <motion.div className="space-y-3" variants={staggerContainer} initial="initial" animate="animate">

                {/* Severity badge */}
                <motion.div variants={staggerItem} className={`flex items-center justify-between border rounded-2xl px-5 py-4 ${sev.bg} ${sev.glow}`}>
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-xl bg-black/20 border border-white/5">
                      <SevIcon size={20} className={sev.color} />
                    </div>
                    <div>
                      <p className="text-[10px] font-sans tracking-widest text-zinc-500 uppercase">Severity</p>
                      <p className={`text-xl font-bold mt-0.5 tracking-wide ${sev.color}`}>{sev.label}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-[10px] font-sans tracking-widest text-zinc-500 uppercase mb-0.5">Type</p>
                    <p className="text-sm text-zinc-300">{report.incident_type}</p>
                  </div>
                </motion.div>

                {/* Title */}
                <motion.h3 variants={staggerItem} className="text-lg font-semibold text-zinc-100 leading-snug px-1">
                  {report.title}
                </motion.h3>

                <ReportSection label="Summary"             content={report.summary}          variants={staggerItem} />

                {/* Timeline */}
                {report.timeline?.length > 0 && (
                  <motion.div variants={staggerItem} className="bg-zinc-900/60 border border-zinc-800 rounded-2xl p-5">
                    <div className="flex items-center gap-2 mb-3">
                      <span className="w-0.5 h-3.5 rounded-full bg-red-500/60" />
                      <p className="text-[10px] font-sans tracking-widest text-zinc-500 uppercase">Timeline</p>
                    </div>
                    <ol className="space-y-2.5">
                      {report.timeline.map((t, i) => (
                        <motion.li key={i} className="flex gap-3 text-sm text-zinc-300"
                          initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                          transition={{ duration: 0.28, delay: 0.1 + i * 0.06, ease: [0.16, 1, 0.3, 1] }}
                        >
                          <span className="text-red-500 font-sans shrink-0 text-xs mt-0.5">{String(i + 1).padStart(2, '0')}</span>
                          <span className="leading-relaxed">{t}</span>
                        </motion.li>
                      ))}
                    </ol>
                  </motion.div>
                )}

                <ReportSection label="Technical Analysis"  content={report.technical_details} variants={staggerItem} />
                <ReportSection label="Impact Assessment"   content={report.impact}            variants={staggerItem} />

                {/* Recommendations */}
                {report.recommendations?.length > 0 && (
                  <motion.div variants={staggerItem} className="bg-zinc-900/60 border border-zinc-800 rounded-2xl p-5">
                    <div className="flex items-center gap-2 mb-3">
                      <span className="w-0.5 h-3.5 rounded-full bg-green-500/60" />
                      <p className="text-[10px] font-sans tracking-widest text-zinc-500 uppercase">What to do now</p>
                    </div>
                    <ul className="space-y-2.5">
                      {report.recommendations.map((r, i) => (
                        <motion.li key={i} className="flex gap-2.5 text-sm text-zinc-300"
                          initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
                          transition={{ duration: 0.28, delay: 0.1 + i * 0.06, ease: [0.16, 1, 0.3, 1] }}
                        >
                          <span className="text-green-500 shrink-0 mt-0.5 text-xs">✓</span>
                          <span className="leading-relaxed">{r}</span>
                        </motion.li>
                      ))}
                    </ul>
                  </motion.div>
                )}

                {/* Legal refs */}
                {report.legal_refs?.length > 0 && (
                  <motion.div variants={staggerItem} className="bg-zinc-900/60 border border-zinc-800 rounded-2xl px-5 py-4">
                    <p className="text-[10px] font-mono tracking-widest text-zinc-500 uppercase mb-2.5">Applicable Law</p>
                    <div className="flex flex-wrap gap-2">
                      {report.legal_refs.map((r, i) => (
                        <span key={i} className="text-xs font-sans text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg px-3 py-1">{r}</span>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Actions */}
                <motion.div variants={staggerItem} className="grid grid-cols-3 gap-2.5 pt-1">
                  {/* Copy */}
                  <motion.button
                    onClick={handleCopy}
                    whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                    className="flex items-center justify-center gap-1.5 py-3 rounded-xl border border-zinc-700/70 hover:border-zinc-600 text-sm text-zinc-400 hover:text-zinc-200 transition-all duration-200"
                  >
                    <AnimatePresence mode="wait">
                      {copied ? (
                        <motion.span key="check" className="flex items-center gap-1.5 text-green-400"
                          initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }}
                        >
                          <TbCheck size={14} /> Copied
                        </motion.span>
                      ) : (
                        <motion.span key="copy" className="flex items-center gap-1.5"
                          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                        >
                          <TbCopy size={14} /> Copy
                        </motion.span>
                      )}
                    </AnimatePresence>
                  </motion.button>

                  {/* Download PDF */}
                  <motion.button
                    onClick={handleDownloadPDF}
                    disabled={pdfLoading}
                    whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                    className="flex items-center justify-center gap-1.5 py-3 rounded-xl border border-red-500/40 hover:border-red-500/70 text-sm text-red-400 hover:text-red-300 disabled:opacity-40 transition-all duration-200"
                  >
                    {pdfLoading ? (
                      <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                      </svg>
                    ) : (
                      <><TbDownload size={14} /> PDF</>
                    )}
                  </motion.button>

                  {/* New Report */}
                  <motion.button
                    onClick={() => { setStep("form"); setReport(null) }}
                    whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
                    className="flex items-center justify-center gap-1.5 py-3 rounded-xl bg-red-600 hover:bg-red-500 text-sm text-white font-semibold transition-colors duration-200"
                  >
                    <TbRefresh size={14} /> New
                  </motion.button>
                </motion.div>

                {/* Emergency strip */}
                <motion.div variants={staggerItem} className="flex items-center justify-between text-xs text-zinc-600 bg-zinc-900/40 border border-zinc-800/50 rounded-xl px-4 py-3">
                  <span>File complaint at cybercrime.gov.in or call</span>
                  <a href="tel:1930" className="text-red-500/70 font-sans font-semibold hover:text-red-400 transition-colors tracking-widest">1930</a>
                </motion.div>

              </motion.div>
            </motion.div>
          )}

        </AnimatePresence>

      </div>
    </div>
  )
}

function ReportSection({ label, content, variants }) {
  if (!content) return null
  return (
    <motion.div variants={variants} className="bg-zinc-900/60 border border-zinc-800 rounded-2xl p-5">
      <div className="flex items-center gap-2 mb-2.5">
        <span className="w-0.5 h-3.5 rounded-full bg-red-500/50" />
        <p className="text-[10px] font-mono tracking-widest text-zinc-500 uppercase">{label}</p>
      </div>
      <p className="text-sm text-zinc-300 leading-relaxed">{content}</p>
    </motion.div>
  )
}

export default FirstAid